spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${URL_OAUTH2:http://localhost:9090}
          jwk-set-uri: ${URL_OAUTH2_JWKS:http://localhost:8081/oauth2/jwks}
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://postgresdb:5432/register_manager_resource_server}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
  jpa:
    show-sql: ${SHOW_SQL:true}
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
      #ddl-auto: none
    properties:
      hibernate.format_sql: ${FORMAT_SQL:true}

server:
  port: ${APP_PORT:9080}

management:
  server:
    port: ${MONITORING_PORT:9081}
  endpoints:
    web:
      exposure:
        include: ${MONITORING_LIST:'*'}
logging:
  file:
    name: ${LOG_NAME:register-manager-resource-server.log}
  level:
    root: ${LOG_LEVEL:warn}
#Trace, debug, info, warn, error